In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

arr1=np.array((1,2,3))
print(arr1)
print(type(arr1))

print(np.__version__)

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
1.20.3


In [8]:
arr=np.array([[1,2],[3,4]])
print(arr.ndim)

arr=np.array([1,2,3,4],ndmin=2)
print(arr)
print(arr.ndim)

2
[[1 2 3 4]]
2


In [13]:
arr=np.array([1,2,3,4])
print(arr[2]+arr[1])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("r,c",arr[0,1])
print(arr[1,-1]) #from last index



5
r,c 2
10


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:4])
print(arr[:4])

print()

print(arr[-3:-1])
print(arr[::2])
print(arr[1:4:2])

[2 3 4]
[1 2 3 4]

[5 6]
[1 3 5 7]
[2 4]


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])

print()

print(arr[0:2,2])
print()
print(arr[0:2,2:])

[7 8 9]

[3 8]

[[ 3  4  5]
 [ 8  9 10]]


In [28]:
print(arr.dtype)

int32


In [29]:
arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr1.dtype)

<U6


In [30]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [31]:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [32]:
arr = np.array([1.4 ,2.4, 3.5, 4.5])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


i = integer
b= boolean
u= unsigned integer
f= float
c= complex float
m= timedelta
M= datetime
O= object
S= string

In [38]:
arr = np.array([1, 0, 6])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [41]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() #copy will not affect original array
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [48]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 42
x = arr.view() #will  affect original array
arr[1] = 6

print(arr)
print(x)

[42  6  3  4  5]
[42  6  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy() #The copy returns None.
                
y = arr.view()  #The view returns the original array.

print(x.base)
print(y.base)

In [53]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr1.shape)

(5,)
(2, 4)


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(2,6)
print(newarr)
print()
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
newarr = arr.reshape(2, 3, 2)
print(newarr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3D array with 2x2 elements:

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


In [66]:
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [80]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [81]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [82]:
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
4
6


In [83]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index,val in np.ndenumerate(arr):
    print(index,val)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [85]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [93]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7 ,8, 9])

arr = np.stack((arr1, arr2,arr3), axis=1)

print(arr)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [94]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [95]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [111]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr=np.array_split(arr,6)
newarr1=np.array_split(arr,2)

print(newarr)
print()
print(newarr1)
print(newarr1[0])
print(newarr1[0][1])

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

[array([1, 2, 3]), array([4, 5, 6])]
[1 2 3]
2


In [112]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1) #3 refers to 3 array

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [114]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x=np.where(arr == 4) #returns indexes where the value is 4
print(x)

(array([3, 5, 6], dtype=int64),)


In [115]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x=np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [118]:
arr = np.array([6, 7, 8, 9])
x=np.searchsorted(arr,7) #Find the indexes where the value 7 should be inserted
x1=np.searchsorted(arr,5)
print(x)
print(x1)

1
0


In [121]:
x2=np.searchsorted(arr,7,side='right')
print(x2)

2


In [124]:
arr1=np.array([1,3,5])
x=np.searchsorted(arr1,[2,4,6]) #maintain the order.
print(x)


[1 2 3]


In [125]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [126]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [130]:
arr = np.array([3, 2, 0, 1])
x=arr[[True,False,False,False]]
print(x)

[3]


In [131]:
filterarr=arr>2
newarr=arr[filterarr]
print(filterarr)
print(newarr)

[ True False False False]
[3]


Random

In [134]:
from numpy import random as r

In [146]:
x=r.randint(10)
x1=r.randint(100,size=(5))
x2=r.randint(100,size=(3,5))
print(x)
print(x1)

print()

print(x2)

9
[37 98 85 21 36]

[[40 67 70 55 87]
 [52  2 68 32 43]
 [35 66 29  1 99]]


In [158]:
x=r.choice([3,5,8])
print(x)

[3 8]
